apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: blue  # Initially points to blue deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000